name: Keep Bot Alive
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install python-telegram-bot psycopg2-binary twelvedata python-dotenv httpx pytz requests matplotlib Pillow numpy pandas mplfinance
      - run: python bot.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TWELVEDATA_KEYS: ${{ secrets.TWELVEDATA_KEYS }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
